### ISSUE TITLE
Getting we made you offline and Searching for GPS, even after turning on both(Parent ID_2164)

### ISSUE THREAD

**Issue by Vinaykm999** [nammayatri/nammayatri#2209] opened 2023-08-03 12:16 UTC
#2164
[Getting we made you offline and Searching for GPS, even after turning on both](https://drive.google.com/file/d/1DmPlqjwUec8yLZ6GbnFx0WQ3WCpkTazU/view?usp=sharing)

Steps:
1. Install yatri partner apk
2. Enter driver number
3. Verify notification

Expected: We should get those notification only Network and GPS turned off

**Comment by Anuragini-2506** [comment] 2023-08-04 13:29
not able to reproduce

**Comment by Rajaprabhu-Natrajan** [comment] 2023-08-07 08:56
Still I can able to reproduce it @Anuragini-2506 . - So I reopen this bug 



cc: @Vinaykm999

**Comment by johnruban-4050** [comment] 2023-08-07 20:02
Retested and working fine as expected in Pixel so im closing this

**Closed by johnruban-4050** 2023-08-07 20:02 UTC
Labels: frontend, QA-Bug
