### ISSUE TITLE
<30/11/23><NYP><ANDROID><Yatri coins><UI issues in Coins><parent id 1980>

### ISSUE THREAD

**Issue by vinod96424** [nammayatri/nammayatri#4505] opened 2023-11-30 06:49 UTC
#1980 

Issues
1. Coins conversion Calculation is incorrect

<img width="374" alt="Screenshot 2023-11-30 at 12 00 00 PM" src="https://github.com/nammayatri/nammayatri/assets/129082995/ecfb10db-3136-41f8-9079-7f16e79ae3f2">

2. Help option is missing

![Screenshot_20231129_153800 (1)](https://github.com/nammayatri/nammayatri/assets/129082995/26374b23-47f2-48e1-bca0-9f55b1d1e5b9)

3.[In coins introduction screen, "Check Now" option is not translated in other respective languages. ](https://drive.google.com/file/d/1EopQR_KV5H_nY0d8lvjG9ZA39YEIFxPv/view?usp=sharing)

4.  [In yatri coins screen, in coins balance cards, The texts "Total earned" and "Coins used" are not aligned properly in tamil language ](https://drive.google.com/file/d/1n7PzLVaEjkIqBZdwdNyJG3xjmk63zu7l/view?usp=sharing)

5. [In tamil language, In yatri Coins screen, Total earned value is not displaying.](https://drive.google.com/file/d/1KDTv2zHC8UPKiWrHX5yzR1IlxMqPulLh/view?usp=drive_link)

6.In earning screen dollar logo is not properly aligned in kannada lanaguage.](https://drive.google.com/file/d/1d2gCgUqvXwn8LCUcRjruqjT7NoK_0nt7/view?usp=sharing)

7. ["Okay" text is missing in "No coins available" screen when selected language is **tamil**
](https://drive.google.com/file/d/148w_Cbvr1Hd1SPTXrRX5I0zN7-H_prtu/view?usp=sharing)

8. "i" button is not clickable-->not able to see the info behind it
![Screenshot_20231130_172150](https://github.com/nammayatri/nammayatri/assets/129082995/7838e3cb-839a-4a65-947a-9d5b30b8e1ba)

**Comment by DwivediAman-exe** [comment] 2023-12-02 16:10
2. Already told you it is not there in the bundle itself why will it show.
6. @Shikhar246 check it please
8. expected

**Comment by vinod96424** [comment] 2023-12-13 14:10
@DwivediAman-exe @Shikhar-24 
7 & 8 issues are reproducing in the latest APK too..

**Comment by DwivediAman-exe** [comment] 2023-12-13 17:26
7th is happening because of there were two translations by someone. fixed now, kindly check.

**Comment by krupal-14** [comment] 2023-12-18 07:58
9.The **destination** text is wrong in kannada language [here](https://drive.google.com/file/d/1PbvI7ns8eTBoFy44cfwX19f4mjN40I4h/view?usp=sharing)
Steps to Reproduce.
1.Launch the apk.
2.Select kannada language.
3.Click on earnings.-->select any past date.
4.Observe the text "destination " ride history.

Actual text: **ತಲುಪಿದ ಸ್ಥಳ**

**Comment by Gowthami1309** [comment] 2023-12-18 12:24
Issue 11: The back navigation arrow is significantly smaller compared to the one in Figma. [Link](https://drive.google.com/file/d/1B-mQyC1zPTHA1PWlpL0N_ofimXKTpWu-/view?usp=sharing)

Issue 12: In the table "Leaderboard - weekly Top 500" a row is missing,  "+" sing is missing before the all numbers. [Link](https://drive.google.com/file/d/15JFLvjLPvPX40bmimhy-Q1kBzGyfM6O5/view?usp=sharing)

Issue 13: In the table, some rows are in Tamil instead of Telugu and vice versa. [Link1](https://drive.google.com/file/d/1z5PNSIestUs49EJmKX_pDnxQc-s0EZ6X/view?usp=sharing) [Link2](https://drive.google.com/file/d/1Kql94kUvy3Qe2LUdWAMO8DCkvP2CrxYO/view?usp=sharing)

Issue 14: In Tamil help is not visible.[ Link](https://drive.google.com/file/d/19P0miShJNi4Wm8Ll2dkzyp_9yAQlWbUf/view?usp=sharing)

Issue 15: In all sections, there is a YouTube video that is not related to coins. Is this expected?

**Comment by DwivediAman-exe** [comment] 2023-12-18 12:40
fixed till 11

**Comment by DwivediAman-exe** [comment] 2023-12-18 13:32
12 - Leaderboard will not be shown, other fixeed
11,13,14,15 - @Shikhar-24

**Comment by Shikhar-24** [comment] 2023-12-18 14:41
15- Vidoes are still in making. Those are kept for now only.

**Comment by krupal-14** [comment] 2023-12-19 08:05
Issue 9 fixed

**Comment by Gowthami1309** [comment] 2023-12-19 10:59
Issue 17: 
[Booking cancellation text should be there instead of ride cancellation , 5-Star text should be as per figma](https://drive.google.com/file/d/13DE8xtv6i7qxWxuzoUydFjhNJ95zRB3Y/view?usp=sharing)

**Comment by Gowthami1309** [comment] 2023-12-19 14:14
Issues 18: Bonus test should be as per figma 
Issue 19 : Today's Earnings should be there instead of Earnings and Extra Bonus should be there instead of Bonus Earned.

**Comment by DwivediAman-exe** [comment] 2023-12-19 16:01
It will not be there. Figma is wrong

**Closed** 2023-12-20 07:14 UTC
Labels: frontend, QA-Bug
