### ISSUE TITLE
Some times app is not launching(Parent_Id-1594)

### ISSUE THREAD

**Issue by krupal-14** [nammayatri/nammayatri#1692] opened 2023-07-14 12:39 UTC
#1594 
**Description**
[Some times app is not launching](https://drive.google.com/file/d/1-2z7DUpCoR5WtghugMMvjLdNfvUyU7OT/view?usp=sharing)

Start watching from 1min

**Steps to Reproduce**
1.Launch the apk
2.Initiate the ride.
3.No driver accepts the ride.
4.Try again pop-up is displayed.
5.Kill the user apk and relaunch.

**Expected Result**
App should Launch

**Actual Result**
App freezes

**Comment by mohdshoaib18169** [comment] 2023-07-20 09:25
fixed

**Comment by rohanrp179** [comment] 2023-07-20 11:48
@tejkranthi @mohdshoaib18169 
[The issue is not fixed. Still present](https://drive.google.com/file/d/18_EVciopXqzjO8H2EqYZI_RIyLh0R6xb/view?usp=sharing)

**Comment by mohdshoaib18169** [comment] 2023-07-21 13:28
@rohanrp179 , it will only happen in master , not in production ,
you can clear it with @tejkranthi

**Comment by rohanrp179** [comment] 2023-07-21 16:05
Sure. Closing the issue @tejkranthi

**Closed by rohanrp179** 2023-07-21 16:05 UTC
Labels: frontend, QA-Bug
