### ISSUE TITLE
01/04/24_NY_Android_Chennai(Rental)_In user application, Getting ANRs frequently after the ride is assigned / started_(Parent id_1980)

### ISSUE THREAD

**Issue by Sumedh-14** [nammayatri/nammayatri#6156] opened 2024-04-01 13:06 UTC
#1980 
[In user application, Getting ANRs frequently after the ride is assigned / started](https://drive.google.com/file/d/1orxHBWGoZ0Zp4OJ2kOqful33dDTbjubH/view?usp=sharing)

Steps: 
1. Launch the application and login with the valid credentials
2. Assign and start a rental ride 
3. Observe the issue

Device Details:
Iqoo Z5

Attachment - https://drive.google.com/file/d/1suZmazJTtMRtQBUpYvVenCTsYJAvQLjK/view?usp=sharing

**Comment by MercyQueen** [comment] 2024-04-02 13:16
Not able to reproduce

**Comment by Vinaykm999** [comment] 2024-04-03 14:06
Working fine now, hence resolving this

**Closed by Vinaykm999** 2024-04-03 14:06 UTC
Labels: QA-Bug
